### ISSUE TITLE
Add English Localation

### ISSUE THREAD

**Issue by ichttt** [ichttt/BackupBasic#5]
Currently, only German is supported

**Comment by chk1** [comment]
Hi, ich könnte die Datei übersetzen, soll ich sie dann einfach BackupBasic_en_US.properties nennen (nach dem Schema der deutschen Datei)?

**Comment by ichttt** [comment]
Ja, wäre super(hab im Moment nicht viel Zeit sonst hätte ich es auch selber gemacht).
